### ISSUE TITLE
Game freezes

### ISSUE THREAD

**Issue by KMFrench1** [su226/StardewValleyMods#1]
The game seems to freeze after I go to bed. Does not happen ever time, but seems to be random.
https://smapi.io/log/4e7cf784cda9460db93b3d8df8147a7e

**Comment by Azzurite** [comment]
This is the stacktrace:

```
[21:48:30 ERROR game] NullReferenceException: Object reference not set to an instance of an object.
   at StardewValley.Game1._newDayAfterFade()+MoveNext() in stardewvalley\Farmer\Farmer\Game1.cs:line 8764
   at StardewValley.Game1.<>c.<newDayAfterFade>b__716_2() in stardewvalley\Farmer\Farmer\Game1.cs:line 8714
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```
